### ISSUE TITLE
Compilation error with ERTS 9.2

### ISSUE THREAD

**Issue by mischov** [mischov/meeseeks_html5ever#9]
Attempts to compile with ERTS 9.2 yield following error

```
error: failed to run custom build command for `erlang_nif-sys v0.6.2`
```

Unable to compile with ERTS 9.2, due to issue with Rustler and erlang_nif-sys. See: https://github.com/hansihe/rustler/issues/115

Awaiting release of Rustler containing merged fix.

**Comment by OvermindDL1** [comment]
Same error, one of my bots is now dead because the server was updated to Elixir 1.6 with ERTS 9.2 because some other things required some functionality from it.  :sob: 

Rustler says it was already updated 12 days 'before' this issue was opened?  :-)
Maybe bind to a github release with the fix for now?  ^.^

**Comment by OvermindDL1** [comment]
Using the github (with subpath) for the mix and changing the Cargo.toml to use the github repo got it working, so it does work, just they really need to release it, however a workaround is available for now?  >.>

**Comment by OvermindDL1** [comment]
And an update has finally been released whoo!

Can meeseeks update it's Cargo.toml file to version `rustler = "^0.16.0"` now?  :-)

I edited my local copy (but my CI is still failing) and it seems to work fine.  :-)

**Comment by OvermindDL1** [comment]
Also update the mix.exs file to version `0.16` as well for rustler (they bumped the mix version to match the rust version)

**Comment by mischov** [comment]
Fixed in v0.8.1.

**Comment by OvermindDL1** [comment]
Whooo!  Thanks much!  I can remove my hack now.  :-)
